# Generated by Django 4.2.3 on 2023-10-07 03:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("courses", "0003_alter_curso_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="curso",
            name="image",
            field=models.ImageField(upload_to="img/"),
        ),
    ]
